import type { FormationMotion } from "./types";

/**
 * 4-2-3-1 공/수 움직임 — 시퀀스 영상 구조.
 *
 * 공격: 기본 진형 (정지) + 좌측 빌드업 시 (7 step) + 우측 빌드업 시 (7 step 미러)
 * 수비: 기본 진형 (정지) + 좌/중/우 침투 시 + 전진 압박 시 (각 1~2 step)
 */

const BASE_FORMATION = [
  { slot: "gk",  x: 50, y: 90 },
  { slot: "lb",  x: 8,  y: 70 },
  { slot: "lcb", x: 34, y: 80 },
  { slot: "rcb", x: 66, y: 80 },
  { slot: "rb",  x: 92, y: 70 },
  { slot: "ldm", x: 45, y: 64 },
  { slot: "rdm", x: 55, y: 64 },
  { slot: "lam", x: 30, y: 46 },
  { slot: "cam", x: 50, y: 40 },
  { slot: "ram", x: 70, y: 46 },
  { slot: "st",  x: 50, y: 26 },
];

export const FORMATION_4231_MOTION: FormationMotion = {
  formationId: "4-2-3-1",

  attack: [
    {
      label: "기본 진형",
      steps: [
        {
          caption: "GK·4백·DM·AM·ST 모두 자기 위치로 정렬. 풀백은 와이드, AM 셋은 미드라인 위, ST 최전방.",
          ball: null,
          positions: BASE_FORMATION,
        },
      ],
    },
    {
      label: "좌측 빌드업 시",
      steps: [
        {
          caption: "1. GK 시작 — 골키퍼가 공 잡고 빌드업 시작.",
          ball: { x: 50, y: 90 },
          positions: BASE_FORMATION,
        },
        {
          caption: "2. GK → LCB — 좌측 센터백에게 짧은 패스. LDM 살짝 빠짐.",
          ball: { x: 32, y: 78 },
          positions: [
            { slot: "gk",  x: 50, y: 88 },
            { slot: "lb",  x: 6,  y: 64 },
            { slot: "lcb", x: 32, y: 78 },
            { slot: "rcb", x: 66, y: 80 },
            { slot: "rb",  x: 92, y: 68 },
            { slot: "ldm", x: 40, y: 60 },
            { slot: "rdm", x: 58, y: 62 },
            { slot: "lam", x: 28, y: 44 },
            { slot: "cam", x: 48, y: 38 },
            { slot: "ram", x: 70, y: 46 },
            { slot: "st",  x: 50, y: 24 },
          ],
        },
        {
          caption: "3. LCB → LDM — 미드필더에게 전진 패스. LB 와이드 + 전진 시작.",
          ball: { x: 40, y: 56 },
          positions: [
            { slot: "gk",  x: 50, y: 86 },
            { slot: "lb",  x: 6,  y: 56 },
            { slot: "lcb", x: 32, y: 74 },
            { slot: "rcb", x: 64, y: 76 },
            { slot: "rb",  x: 90, y: 64 },
            { slot: "ldm", x: 40, y: 56 },
            { slot: "rdm", x: 58, y: 58 },
            { slot: "lam", x: 24, y: 38 },
            { slot: "cam", x: 46, y: 32 },
            { slot: "ram", x: 70, y: 42 },
            { slot: "st",  x: 50, y: 22 },
          ],
        },
        {
          caption: "4. LDM → LB — 좌측 풀백에게 사이드 패스. LB 본격 오버랩.",
          ball: { x: 12, y: 42 },
          positions: [
            { slot: "gk",  x: 50, y: 84 },
            { slot: "lb",  x: 12, y: 42 },
            { slot: "lcb", x: 30, y: 68 },
            { slot: "rcb", x: 62, y: 70 },
            { slot: "rb",  x: 88, y: 56 },
            { slot: "ldm", x: 38, y: 54 },
            { slot: "rdm", x: 56, y: 54 },
            { slot: "lam", x: 22, y: 30 },
            { slot: "cam", x: 44, y: 26 },
            { slot: "ram", x: 68, y: 36 },
            { slot: "st",  x: 50, y: 18 },
          ],
        },
        {
          caption: "5. LB → LAM — 안쪽 컷인 패스. LAM 이 사이공간에서 받음.",
          ball: { x: 22, y: 28 },
          positions: [
            { slot: "gk",  x: 50, y: 82 },
            { slot: "lb",  x: 10, y: 32 },
            { slot: "lcb", x: 30, y: 64 },
            { slot: "rcb", x: 60, y: 66 },
            { slot: "rb",  x: 86, y: 50 },
            { slot: "ldm", x: 38, y: 50 },
            { slot: "rdm", x: 56, y: 50 },
            { slot: "lam", x: 22, y: 28 },
            { slot: "cam", x: 42, y: 22 },
            { slot: "ram", x: 64, y: 30 },
            { slot: "st",  x: 50, y: 14 },
          ],
        },
        {
          caption: "6. LAM → LB(크로스) — LB 가 다시 사이드 라인까지 침투, 크로스 직전.",
          ball: { x: 8, y: 14 },
          positions: [
            { slot: "gk",  x: 50, y: 80 },
            { slot: "lb",  x: 8,  y: 14 },
            { slot: "lcb", x: 32, y: 56 },
            { slot: "rcb", x: 60, y: 58 },
            { slot: "rb",  x: 82, y: 36 },
            { slot: "ldm", x: 38, y: 46 },
            { slot: "rdm", x: 56, y: 44 },
            { slot: "lam", x: 30, y: 14 },
            { slot: "cam", x: 46, y: 10 },
            { slot: "ram", x: 60, y: 14 },
            { slot: "st",  x: 50, y: 10 },
          ],
        },
        {
          caption: "7. 크로스 → ST 마무리! — 박스 안 ST 가 헤더로 슛.",
          ball: { x: 50, y: 4 },
          positions: [
            { slot: "gk",  x: 50, y: 78 },
            { slot: "lb",  x: 12, y: 14 },
            { slot: "lcb", x: 34, y: 50 },
            { slot: "rcb", x: 60, y: 52 },
            { slot: "rb",  x: 78, y: 32 },
            { slot: "ldm", x: 40, y: 40 },
            { slot: "rdm", x: 56, y: 40 },
            { slot: "lam", x: 32, y: 8 },
            { slot: "cam", x: 46, y: 6 },
            { slot: "ram", x: 60, y: 10 },
            { slot: "st",  x: 50, y: 4 },
          ],
        },
      ],
    },
    {
      label: "우측 빌드업 시",
      steps: [
        {
          caption: "1. GK 시작 — 골키퍼가 공 잡고 빌드업 시작.",
          ball: { x: 50, y: 90 },
          positions: BASE_FORMATION,
        },
        {
          caption: "2. GK → RCB — 우측 센터백에게 짧은 패스. RDM 살짝 빠짐.",
          ball: { x: 68, y: 78 },
          positions: [
            { slot: "gk",  x: 50, y: 88 },
            { slot: "lb",  x: 8,  y: 68 },
            { slot: "lcb", x: 34, y: 80 },
            { slot: "rcb", x: 68, y: 78 },
            { slot: "rb",  x: 94, y: 64 },
            { slot: "ldm", x: 42, y: 62 },
            { slot: "rdm", x: 60, y: 60 },
            { slot: "lam", x: 30, y: 46 },
            { slot: "cam", x: 52, y: 38 },
            { slot: "ram", x: 72, y: 44 },
            { slot: "st",  x: 50, y: 24 },
          ],
        },
        {
          caption: "3. RCB → RDM — 미드필더에게 전진 패스. RB 와이드 + 전진 시작.",
          ball: { x: 60, y: 56 },
          positions: [
            { slot: "gk",  x: 50, y: 86 },
            { slot: "lb",  x: 10, y: 64 },
            { slot: "lcb", x: 36, y: 76 },
            { slot: "rcb", x: 68, y: 74 },
            { slot: "rb",  x: 94, y: 56 },
            { slot: "ldm", x: 42, y: 58 },
            { slot: "rdm", x: 60, y: 56 },
            { slot: "lam", x: 30, y: 42 },
            { slot: "cam", x: 54, y: 32 },
            { slot: "ram", x: 76, y: 38 },
            { slot: "st",  x: 50, y: 22 },
          ],
        },
        {
          caption: "4. RDM → RB — 우측 풀백에게 사이드 패스. RB 본격 오버랩.",
          ball: { x: 88, y: 42 },
          positions: [
            { slot: "gk",  x: 50, y: 84 },
            { slot: "lb",  x: 12, y: 56 },
            { slot: "lcb", x: 38, y: 70 },
            { slot: "rcb", x: 70, y: 68 },
            { slot: "rb",  x: 88, y: 42 },
            { slot: "ldm", x: 44, y: 54 },
            { slot: "rdm", x: 62, y: 54 },
            { slot: "lam", x: 32, y: 36 },
            { slot: "cam", x: 56, y: 26 },
            { slot: "ram", x: 78, y: 30 },
            { slot: "st",  x: 50, y: 18 },
          ],
        },
        {
          caption: "5. RB → RAM — 안쪽 컷인 패스. RAM 이 사이공간에서 받음.",
          ball: { x: 78, y: 28 },
          positions: [
            { slot: "gk",  x: 50, y: 82 },
            { slot: "lb",  x: 14, y: 50 },
            { slot: "lcb", x: 40, y: 66 },
            { slot: "rcb", x: 70, y: 64 },
            { slot: "rb",  x: 90, y: 32 },
            { slot: "ldm", x: 44, y: 50 },
            { slot: "rdm", x: 62, y: 50 },
            { slot: "lam", x: 36, y: 30 },
            { slot: "cam", x: 58, y: 22 },
            { slot: "ram", x: 78, y: 28 },
            { slot: "st",  x: 50, y: 14 },
          ],
        },
        {
          caption: "6. RAM → RB(크로스) — RB 가 다시 사이드 라인까지 침투, 크로스 직전.",
          ball: { x: 92, y: 14 },
          positions: [
            { slot: "gk",  x: 50, y: 80 },
            { slot: "lb",  x: 18, y: 36 },
            { slot: "lcb", x: 40, y: 58 },
            { slot: "rcb", x: 68, y: 56 },
            { slot: "rb",  x: 92, y: 14 },
            { slot: "ldm", x: 44, y: 44 },
            { slot: "rdm", x: 62, y: 46 },
            { slot: "lam", x: 40, y: 14 },
            { slot: "cam", x: 54, y: 10 },
            { slot: "ram", x: 70, y: 14 },
            { slot: "st",  x: 50, y: 10 },
          ],
        },
        {
          caption: "7. 크로스 → ST 마무리! — 박스 안 ST 가 헤더로 슛.",
          ball: { x: 50, y: 4 },
          positions: [
            { slot: "gk",  x: 50, y: 78 },
            { slot: "lb",  x: 22, y: 32 },
            { slot: "lcb", x: 40, y: 52 },
            { slot: "rcb", x: 66, y: 50 },
            { slot: "rb",  x: 88, y: 14 },
            { slot: "ldm", x: 44, y: 40 },
            { slot: "rdm", x: 60, y: 40 },
            { slot: "lam", x: 40, y: 10 },
            { slot: "cam", x: 54, y: 6 },
            { slot: "ram", x: 68, y: 8 },
            { slot: "st",  x: 50, y: 4 },
          ],
        },
      ],
    },
  ],

  defense: [
    {
      label: "기본 진형",
      steps: [
        {
          caption: "AM 양 윙(LAM·RAM)이 미드라인까지 내려와 4-4-1-1 형태. CAM 은 ST 옆 듀오. 상대 빌드업 트리거 대기.",
          ball: null,
          positions: [
            { slot: "gk",  x: 50, y: 92 },
            { slot: "lb",  x: 20, y: 78 },
            { slot: "lcb", x: 40, y: 82 },
            { slot: "rcb", x: 60, y: 82 },
            { slot: "rb",  x: 80, y: 78 },
            { slot: "ldm", x: 38, y: 64 },
            { slot: "rdm", x: 62, y: 64 },
            { slot: "lam", x: 14, y: 54 },
            { slot: "cam", x: 50, y: 48 },
            { slot: "ram", x: 86, y: 54 },
            { slot: "st",  x: 50, y: 38 },
          ],
        },
      ],
    },
    {
      label: "상대 우측 전개 시",
      steps: [
        {
          caption: "상대가 자기 우측으로 전개 — 라인 전체 좌측·전방 시프트. LAM 1차 압박, ST 같은 측 합세, LB 윙어 마크. RB·RAM 안쪽 cover.",
          ball: { x: 18, y: 18 },
          positions: [
            { slot: "gk",  x: 45, y: 86 },
            { slot: "lb",  x: 14, y: 42 },
            { slot: "lcb", x: 30, y: 60 },
            { slot: "rcb", x: 50, y: 62 },
            { slot: "rb",  x: 66, y: 58 },
            { slot: "ldm", x: 28, y: 44 },
            { slot: "rdm", x: 52, y: 48 },
            { slot: "lam", x: 16, y: 24 },
            { slot: "cam", x: 40, y: 36 },
            { slot: "ram", x: 64, y: 42 },
            { slot: "st",  x: 32, y: 24 },
          ],
        },
      ],
    },
    {
      label: "상대 중앙 전개 시",
      steps: [
        {
          caption: "상대가 중앙 DM 통해 전개 — CAM 이 적정 거리에서 DM 견제, ST 가 그 위에서 CB→DM 횡패스 차단. 4백 라인 좁혀 통로 봉쇄.",
          ball: { x: 50, y: 18 },
          positions: [
            { slot: "gk",  x: 50, y: 88 },
            { slot: "lb",  x: 22, y: 70 },
            { slot: "lcb", x: 42, y: 74 },
            { slot: "rcb", x: 58, y: 74 },
            { slot: "rb",  x: 78, y: 70 },
            { slot: "ldm", x: 40, y: 50 },
            { slot: "rdm", x: 60, y: 50 },
            { slot: "lam", x: 22, y: 44 },
            { slot: "cam", x: 45, y: 32 },
            { slot: "ram", x: 78, y: 44 },
            { slot: "st",  x: 55, y: 26 },
          ],
        },
      ],
    },
    {
      label: "상대 좌측 전개 시",
      steps: [
        {
          caption: "상대가 자기 좌측으로 전개 — 라인 전체 우측·전방 시프트. RAM 1차 압박, ST 같은 측 합세, RB 윙어 마크. LB·LAM 안쪽 cover.",
          ball: { x: 82, y: 18 },
          positions: [
            { slot: "gk",  x: 55, y: 86 },
            { slot: "lb",  x: 34, y: 58 },
            { slot: "lcb", x: 50, y: 62 },
            { slot: "rcb", x: 70, y: 60 },
            { slot: "rb",  x: 86, y: 42 },
            { slot: "ldm", x: 48, y: 48 },
            { slot: "rdm", x: 72, y: 44 },
            { slot: "lam", x: 36, y: 42 },
            { slot: "cam", x: 60, y: 36 },
            { slot: "ram", x: 84, y: 24 },
            { slot: "st",  x: 68, y: 24 },
          ],
        },
      ],
    },
    {
      label: "전방 압박",
      steps: [
        {
          caption: "상대 빌드업 미스 트리거 — 라인 전체를 더 올려 high-press. ST 가 상대 CB 견제, CAM 이 DM 차단, 윙어가 풀백 차단.",
          ball: { x: 50, y: 8 },
          positions: [
            { slot: "gk",  x: 50, y: 72 },
            { slot: "lb",  x: 22, y: 52 },
            { slot: "lcb", x: 42, y: 58 },
            { slot: "rcb", x: 58, y: 58 },
            { slot: "rb",  x: 78, y: 52 },
            { slot: "ldm", x: 38, y: 38 },
            { slot: "rdm", x: 62, y: 38 },
            { slot: "lam", x: 18, y: 28 },
            { slot: "cam", x: 44, y: 24 },
            { slot: "ram", x: 82, y: 28 },
            { slot: "st",  x: 56, y: 18 },
          ],
        },
      ],
    },
  ],
};
